apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: adwf7202h-go
  janus-idp.io/tekton: adwf7202h-go
  backstage.io/kubernetes-id: adwf7202h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: adwf7202h-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
